import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { repo, commit, cli, git, pkg } from "./helpers.mjs";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const policy = (manager = "pnpm", enforcement = "block") => JSON.stringify({ version: 1, decisions: [{ key: "package.manager", allowed: [manager], enforcement }] }, null, 2) + "\n";

test("contract init writes only safe package-manager and Node decisions", () => {
  const dir = repo({
    "package.json": pkg({ "drizzle-orm": "0.45" }, { packageManager: "pnpm@10", engines: { node: "22.x" } }),
    "pnpm-lock.yaml": "x\n",
  });
  const result = cli(dir, "contract", "init", dir);
  assert.equal(result.code, 0);
  assert.match(result.out, /Created \.crosscheck\/contract\.json/);
  const value = JSON.parse(readFileSync(join(dir, ".crosscheck", "contract.json"), "utf8"));
  assert.deepEqual(value.decisions.map((item) => item.key), ["package.manager", "runtime.node"]);
  assert.equal(value.decisions.some((item) => item.key === "database.orm"), false);
});

test("contract init refuses to overwrite unless --force is supplied", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy() });
  assert.equal(cli(dir, "contract", "init", dir).code, 2);
  assert.equal(cli(dir, "contract", "init", dir, "--force").code, 0);
});

test("contract init --force can replace a malformed existing policy", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": "{" });
  assert.equal(cli(dir, "contract", "init", dir, "--force").code, 0);
  assert.equal(JSON.parse(readFileSync(join(dir, ".crosscheck", "contract.json"), "utf8")).decisions[0].allowed[0], "pnpm");
});

test("contract suggest is JSON-capable and never modifies policy", () => {
  const dir = repo({ "package.json": pkg({ "@prisma/client": "6", "@clerk/nextjs": "6", pg: "8" }), "prisma/schema.prisma": 'datasource db {\n provider = "postgresql"\n}\n' });
  const result = cli(dir, "contract", "suggest", dir, "--format", "json").json();
  assert.deepEqual(result.suggestions.map((item) => item.key), ["auth.provider", "database.engine", "database.orm"]);
  assert.equal(existsSync(join(dir, ".crosscheck", "contract.json")), false);
});

test("context text and JSON are deterministic", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy() });
  const first = cli(dir, "context", dir).out;
  assert.equal(first, cli(dir, "context", dir).out);
  assert.match(first, /CrossCheck Repository Decisions/);
  const json = cli(dir, "context", dir, "--format", "json").json();
  assert.match(json.contractDigest, /^[a-f0-9]{64}$/);
  assert.equal(json.decisions[0].key, "package.manager");
});

test("context --write creates deterministic AGENT_CONTEXT.md", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy() });
  assert.equal(cli(dir, "context", dir, "--write").code, 0);
  const target = join(dir, ".crosscheck", "AGENT_CONTEXT.md");
  const first = readFileSync(target, "utf8");
  assert.match(first, /Do not edit this file manually/);
  assert.doesNotMatch(first, /\d{4}-\d{2}-\d{2}T/);
  cli(dir, "context", dir, "--write");
  assert.equal(readFileSync(target, "utf8"), first);
});

test("context without a contract and invalid contracts exit 2", () => {
  assert.equal(cli(repo({ "package.json": {} }), "context").code, 2);
  const invalid = repo({ "package.json": {}, ".crosscheck/contract.json": "{" });
  const result = cli(invalid);
  assert.equal(result.code, 2);
  assert.match(result.err, /invalid JSON/);
});

test("CLI enforces base-contract authority and explicit migration approval", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy("pnpm") });
  const base = git(dir, "rev-parse", "HEAD").trim();
  commit(dir, { "package.json": { packageManager: "npm@11" }, "pnpm-lock.yaml": null, "package-lock.json": "{}\n", ".crosscheck/contract.json": policy("npm") }, "migrate");
  const blocked = cli(dir, "--base", base, "--head", "HEAD", "--fail-on", "new", "--format", "json");
  assert.equal(blocked.code, 1);
  assert.equal(blocked.json().introduced.some((item) => item.rule === "contract/change-unapproved"), true);
  const approved = cli(dir, "--base", base, "--head", "HEAD", "--allow-contract-change", "--fail-on", "new", "--format", "json");
  assert.equal(approved.code, 0);
  assert.equal(approved.json().contractChangeApproved, true);
});

test("contract warning is reported but does not fail --fail-on any", () => {
  const dir = repo({ "package.json": { packageManager: "npm@11" }, "package-lock.json": "{}\n", ".crosscheck/contract.json": policy("pnpm", "warn") });
  const result = cli(dir, "--fail-on", "any", "--format", "json");
  assert.equal(result.code, 0);
  assert.equal(result.json().findings.some((item) => item.tier === "contract" && item.enforcement === "warn"), true);
});

test("GitHub annotation anchors a contract violation to introduced evidence", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy() });
  const base = git(dir, "rev-parse", "HEAD").trim();
  commit(dir, { "package-lock.json": "{}\n" });
  const result = cli(dir, "--base", base, "--head", "HEAD", "--format", "github", "--fail-on", "new");
  assert.equal(result.code, 1);
  assert.match(result.out, /^::error file=package-lock\.json,line=1,title=CrossCheck/m);
});

test("unapproved migration annotation anchors to the contract", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy("pnpm") });
  const base = git(dir, "rev-parse", "HEAD").trim();
  commit(dir, { ".crosscheck/contract.json": policy("npm") });
  const result = cli(dir, "--base", base, "--head", "HEAD", "--format", "github", "--fail-on", "new");
  assert.match(result.out, /^::error file=\.crosscheck\/contract\.json,line=1,title=/m);
  assert.match(result.out, /repository decision changes/i);
});

test("markdown and JSON identify the authoritative contract and decision changes", () => {
  const dir = repo({ "package.json": { packageManager: "pnpm@10" }, "pnpm-lock.yaml": "x\n", ".crosscheck/contract.json": policy("pnpm") });
  const base = git(dir, "rev-parse", "HEAD").trim();
  commit(dir, { "package.json": { packageManager: "npm@11" }, "pnpm-lock.yaml": null, "package-lock.json": "{}\n", ".crosscheck/contract.json": policy("npm") });
  const markdown = cli(dir, "--base", base, "--head", "HEAD", "--format", "markdown").out;
  assert.match(markdown, /## Repository decision contract/);
  assert.match(markdown, /##? Repository decision changes/);
  assert.match(markdown, /approval required/);
  const json = cli(dir, "--base", base, "--head", "HEAD", "--format", "json").json();
  assert.equal(json.contract.decisions[0].allowed[0], "pnpm", "base contract remains authority");
  assert.equal(json.proposedContract.decisions[0].allowed[0], "npm");
});

test("help and Action metadata expose contract controls and outputs", () => {
  assert.match(cli(repo({}), "--help").out, /contract init/);
  assert.match(cli(repo({}), "--help").out, /--allow-contract-change/);
  const action = readFileSync(join(ROOT, "action.yml"), "utf8");
  for (const value of ["allow-contract-change", "contract-violations", "decision-changes", "contract-digest", "crosscheck:decision-change"]) assert.match(action, new RegExp(value));
});
